# Generated by Django 5.0.6 on 2024-07-30 07:19

import django.utils.timezone
import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0032_alter_stock_stock_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=transactions.models.generate_transaction_id,
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "date_transaction",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("sold_to", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stock_items",
                    models.ManyToManyField(
                        null=True, related_name="items_to_sell", to="home.stock"
                    ),
                ),
            ],
        ),
    ]
