# Generated by Django 4.1 on 2024-08-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_stock_stock_name'),
        ('transactions', '0002_sellitem_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=8)),
                ('date_transaction', models.DateField()),
                ('sold_to', models.CharField(blank=True, max_length=255, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_items', models.ManyToManyField(related_name='transaction_logs', to='home.stock')),
            ],
        ),
    ]
