# Generated by Django 4.1 on 2024-08-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
