# Generated by Django 5.0.3 on 2024-08-31 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_alter_stock_stock_name"),
        ("transactions", "0004_delete_transactionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellitem",
            name="date_transaction",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sellitem",
            name="stock_items",
            field=models.ManyToManyField(
                blank=True, related_name="items_to_sell", to="home.stock"
            ),
        ),
    ]
