# Generated by Django 5.0.3 on 2024-09-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_sellitem_total_margin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellitem",
            name="sold_to",
            field=models.CharField(
                blank=True, default="Customer Name", max_length=255, null=True
            ),
        ),
    ]
