# Generated by Django 5.0.3 on 2024-05-30 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Specify the Product Category. Note that this will be reused for each product.",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                default="Product 1", help_text="Official product name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="SKU",
            field=models.CharField(
                help_text="SKU is a unique ID given mainly by manufacturers. Check the Unit or Documents if SKU is present.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Tell something about the product."),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.category"
            ),
        ),
    ]
