# Generated by Django 5.0.3 on 2024-05-30 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing",
            name="product",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.category",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.product",
            ),
        ),
    ]
