# Generated by Django 5.0.6 on 2024-06-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_supplier_email_supplier_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.supplier'),
        ),
    ]
