# Generated by Django 5.0.6 on 2024-06-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_stock_product_alter_stock_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.supplier'),
        ),
    ]
