# Generated by Django 5.0.6 on 2024-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_category_category_alter_stock_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='Gasul_X', max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_last_ordered',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_received',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
    ]
