# Generated by Django 5.0.6 on 2024-06-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_stock_stock_name_alter_stock_date_last_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='Wonder Gasul', max_length=255),
        ),
    ]
