# Generated by Django 5.0.6 on 2024-06-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_stock_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='Gas Gas Gas!', max_length=255),
        ),
    ]
