# Generated by Django 5.0.3 on 2024-06-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_stock_id_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Wonder Gasul", max_length=255),
        ),
    ]
