# Generated by Django 5.0.3 on 2024-06-06 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="date_received",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="YYYY-MM-DD"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Gasul na Cool", max_length=255),
        ),
    ]
