# Generated by Django 5.0.3 on 2024-06-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_stock_date_received_alter_stock_stock_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="quantity",
        ),
    ]
