# Generated by Django 5.0.3 on 2024-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_remove_stock_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="minimum_quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="YYYY-MM-DD (Leave Blank if N/A)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Gasul X", max_length=255),
        ),
    ]
