# Generated by Django 5.0.3 on 2024-06-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_remove_stock_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Gas Gas Gas!", max_length=255),
        ),
    ]
