# Generated by Django 5.0.3 on 2024-06-20 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="YYYY-MM-DD (Leave Blank if N/A)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Awesome Gasul", max_length=255),
        ),
    ]
