# Generated by Django 5.0.3 on 2024-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="YYYY-MM-DD (Expiry defaults with product category expiry)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Wonder Gasul", max_length=255),
        ),
    ]
