# Generated by Django 5.0.3 on 2024-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="YYYY-MM-DD (Expiry defaults with product category expiry)",
                null=True,
            ),
        ),
    ]
