# Generated by Django 5.0.3 on 2024-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_alter_stock_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Wonder Gasul", max_length=255),
        ),
    ]
