# Generated by Django 5.0.3 on 2024-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0028_alter_stock_product_alter_stock_stock_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                    ("phased_out", "Phased Out"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Oh my Gas", max_length=255),
        ),
    ]
