# Generated by Django 5.0.6 on 2024-07-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Gasul na Cool", max_length=255),
        ),
    ]
