# Generated by Django 5.0.3 on 2024-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_stock_is_sold_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Wonder Gasul", max_length=255),
        ),
    ]
