# Generated by Django 5.0.3 on 2024-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Gasul X", max_length=255),
        ),
    ]
