# Generated by Django 5.0.3 on 2024-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="sold_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
