# Generated by Django 4.1 on 2024-08-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_stock_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='Gas Gas Gas!', max_length=255),
        ),
    ]
