# Generated by Django 4.1 on 2024-09-11 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_stock_date_received_alter_stock_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='YYYY-MM-DD: HH-MM'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='Gasul na Cool', max_length=255),
        ),
    ]
