# Generated by Django 5.0.3 on 2024-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0045_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="margin",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Awesome Gasul", max_length=255),
        ),
    ]
