# Generated by Django 5.0.3 on 2024-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0046_product_margin_alter_stock_stock_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_name",
            field=models.CharField(default="Wonder Gasul", max_length=255),
        ),
    ]
